<?php

namespace FNC\Bundle\AccountServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryRepository extends EntityRepository
{
    /**
     * @param Account $account
     * @param string  $transactionCode
     * @return History
     */
    public function findOneByAccountAndTransactionCode(Account $account, $transactionCode)
    {
        return $this->findOneBy(
            array(
                'account' => $account,
                'transactionCode' => $transactionCode
            )
        );
    }

    /**
     * @param Account $account
     * @param string  $transactionCode
     * @return integer
     */
    public function findSumByAccountAndTransactionCode(Account $account, $transactionCode)
    {
        $dql = "SELECT SUM(e.amount) AS amount FROM FNC\AccountBundle\Entity\History e " .
            "WHERE e.account = ?1 AND e.transactionCode = ?2";

        $em = $this->getEntityManager();

        $amount = $em->createQuery($dql)
            ->setParameter(1, $account)
            ->setParameter(2, $transactionCode)
            ->getSingleScalarResult();

        return $amount;
    }
}
