management_account:
    path:     /
    defaults: { _controller: "FNCAccountBundle:Account:index" }

management_account_show:
    path:     /{id}/show
    defaults: { _controller: "FNCAccountBundle:Account:show" }

management_account_new:
    path:     /new
    defaults: { _controller: "FNCAccountBundle:Account:new" }

management_account_create:
    path:     /create
    defaults: { _controller: "FNCAccountBundle:Account:create" }
    requirements: { _method: post }

management_account_edit:
    path:     /{id}/edit
    defaults: { _controller: "FNCAccountBundle:Account:edit" }

management_account_update:
    path:     /{id}/update
    defaults: { _controller: "FNCAccountBundle:Account:update" }
    requirements: { _method: post|put }

management_account_delete:
    path:     /{id}/delete
    defaults: { _controller: "FNCAccountBundle:Account:delete" }
    requirements: { _method: post|delete }

management_account_booking:
    path:     /{id}/booking
    defaults: { _controller: "FNCAccountBundle:Account:booking" }
